version: '3.8'
services:
  es:
    image: rasenshuriken/elasticsearch_no_security:8.6.1
    ports: 
      - 9200:9200

  app:
    image: vishnutheep/spring:latest
    ports: 
      - 8080:8080
    
      