# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Java with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean install
        
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & Push Spring-Boot Docker image
      with:
        image: vishnutheep/spring
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy compose and run in server
      run: |
        echo "$TEST_KEY" > test_key.pem
        sudo chmod 400 test_key.pem
        scp -o StrictHostKeyChecking=no -i test_key.pem backend-db.yml ubuntu@18.209.62.194:/home/ubuntu/backend.yml
        ssh -o StrictHostKeyChecking=no -i test_key.pem ubuntu@18.209.62.194 "sudo docker compose -f /home/ubuntu/backend.yml up"

      env:
        TEST_KEY: ${{ secrets.TEST_KEY }}

      
      
