name: Build Java with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean install
        
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & Push Spring-Boot Docker image
      with:
        image: vishnutheep/spring
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy compose and run in server
      run: |
        echo "$TEST_KEY" > test_key.pem
        sudo chmod 400 test_key.pem
        ssh -tt -i test_key.pem ubuntu@18.209.62.194

      env:
        TEST_KEY: ${{ secrets.TEST_KEY }}

      
      
